pipeline {
    agent any

    tools {
        nodejs "nodejs"   // Must match Jenkins NodeJS installation name
        // Sonar scanner will be invoked via withSonarQubeEnv, no need to declare here
    }

    environment {
        APP_DIR = 'mern/frontend'
    }

    stages {

        stage('Install Dependencies') {
            steps {
                dir(env.APP_DIR) {
                    sh 'npm install --no-audit'
                }
            }
        }

        stage('Auto Fix Vulnerabilities') {
            steps {
                dir(env.APP_DIR) {
                    sh 'npm audit fix || true'
                }
            }
        }
        
        stage('Security Audit Check') {
            steps {
                dir(env.APP_DIR) {
                    sh 'npm audit --audit-level=critical'
                }
            }
        }

        stage('Unit Test + Coverage') {
            steps {
                dir(env.APP_DIR) {
                     catchError(buildResult: 'SUCCESS', message: 'It will be fixed later as no test file', stageResult: 'UNSTABLE'){
                        sh 'npm test --coverage'
                     }
                    
                }
            }
        }

       // sonar authentication and collects code and coverage report
        stage('SonarQube Scan') {
            steps {
                withSonarQubeEnv('SonarServer') {  
                    dir(env.APP_DIR) {
                       sh '/opt/sonar-scanner/bin/sonar-scanner'
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                    timeout(time: 5, unit: 'MINUTES') {
                        waitForQualityGate abortPipeline: false
                    }
            
            }
        }
    }
}

