pipeline {
    agent any

    tools {
        nodejs "nodejs"   // Must match Jenkins NodeJS installation name
    }

    environment {
        APP_DIR = 'mern/frontend'
        AWS_ACCOUNT_ID = credentials('ACCOUNT_ID')
        AWS_DEFAULT_REGION = 'us-east-1'
        frontend_REPO_NAME= 'mern-frontend'
        backend_REPO_NAME= 'mern-backend'
        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"
    }

    stages {

        stage('Install Dependencies') {
            steps {
                dir(env.APP_DIR) {
                    sh 'npm install --no-audit'
                }
            }
        }

        stage('Auto Fix Vulnerabilities') {
            steps {
                dir(env.APP_DIR) {
                    sh 'npm audit fix || true'
                }
            }
        }
        
        stage('Security Audit Check') {
            steps {
                dir(env.APP_DIR) {
                    sh 'npm audit --audit-level=critical'
                }
            }
        }

        stage('Unit Test + Coverage') {
            steps {
                dir(env.APP_DIR) {
                     catchError(buildResult: 'SUCCESS', message: 'It will be fixed later as no test file', stageResult: 'UNSTABLE'){
                        sh 'npm test --coverage'
                     }
                    
                }
            }
        }

       // sonar authentication and collects code and coverage report
        stage('SonarQube Scan') {
            steps {
                withSonarQubeEnv('SonarServer') {  
                    dir(env.APP_DIR) {
                       sh '/opt/sonar-scanner/bin/sonar-scanner'
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                catchError(buildResult: 'SUCCESS', message: 'It will be fixed later as no test file', stageResult: 'UNSTABLE')
                {
                timeout(time: 5, unit: 'MINUTES') {
                                        waitForQualityGate abortPipeline: true
                                    }
                }                   
            
            }
        }
        
        stage (" Building docker image"){
            steps{
                dir(env.APP_DIR){
                    sh 'docker build -t ${frontend_REPO_NAME}:${BUILD_NUMBER} .'
                }
            }
        }


        stage("ECR Image Pushing") {
            steps {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-credentials'
                    ]]) {
                        sh '''
                        aws ecr get-login-password --region ${AWS_DEFAULT_REGION} \
                        | docker login --username AWS --password-stdin ${REPOSITORY_URI}

                        docker tag ${frontend_REPO_NAME} \
                            ${REPOSITORY_URI}${frontend_REPO_NAME}:${BUILD_NUMBER}

                        docker push ${REPOSITORY_URI}${frontend_REPO_NAME}:${BUILD_NUMBER}
                        '''
                    }
                }
        }
    }
}

